version: '2'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3306"
    volumes:
      - ./mysql/:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/old-dragon-manager-api
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development