default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root123456
  host: database
  port: 3306

development:
  <<: *default
  database: old_dragon_manager_development

test:
  <<: *default
  database: old_dragon_manager_test

production:
  <<: *default
  database: old_dragon_manager_production
  username: old_dragon_manager
  password: <%= ENV['OLD_DRAGON_MANAGER_DATABASE_PASSWORD'] %>