# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfddc5f82d258e991ad19704df917bd5f7766c250bcd8a69c6ab228b5d6d6df0aece683ad06257410f717ff9f579494e4e41cb1fda0d8428ac6af774a1c4f0c8
  token_signature: 0c7ea3c11407051ac7f4615bb6dc29db844933fbc5c7fbde3d51d6831e0391d6c9ef5615484a5ef89b7c72b5491ae9a303d67ed697d5a1a2cda524c176d75a87

test:
  secret_key_base: e17a071be5cbd85b65638ee065e01af7668b4e648524cb584f840f8189a836a681b839ecf083b5e6b24273483ed44e412770f9346fa0968fb90dee56054c3bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
